# Mark Shust's Docker Configuration for Magento (https://github.com/markshust/docker-magento)
# Version 29.0.0

version: "3"

services:
  app:
    image: markoshust/magento-nginx:1.13-8
    environment:
      - VIRTUAL_HOST=myhost.example.com
      - VIRTUAL_PROTO=https
      - VIRTUAL_PORT=8443
      - LETSENCRYPT_HOST=myhost.example.com
    links:
      - phpfpm
    volumes: &appvolumes
      - ~/.composer:/var/www/.composer:delegated
      - ./src:/var/www/html
      - sockdata:/sock
      - ssldata:/etc/nginx/certs

  phpfpm:
    image: markoshust/magento-php:7.3-fpm-4
    volumes: *appvolumes

  redis:
    image: redis:5.0

  elasticsearch:
    image: markoshust/magento-elasticsearch:6.5.4-0
    ports:
      - "9200:9200"
      - "9300:9300"

  rabbitmq:
    image: rabbitmq:3.7-management
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - rabbitmqdata:/var/lib/rabbitmq

  # Disabling cron by default as it uses higher CPU, enable if needed
  #cron:
  #  image: markoshust/magento-php:7.3-fpm-4
  #  user: root
  #  command: /usr/local/bin/cronstart
  #  tty: true
  #  links:
  #    - db
  #  volumes: *appvolumes

volumes:
  rabbitmqdata:
  sockdata:
  ssldata:
